### ISSUE TITLE
im getting this error i have followed everything properly

### ISSUE THREAD

**Issue by chiragvshroff** [kimocoder/rtl8188eus#11]
when i enter make this is what comes

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.17.0-kali1-amd64/build M=/root/rtl8188eus  modules
make[1]: *** /lib/modules/4.17.0-kali1-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:2061: modules] Error 2

**Comment by kimocoder** [comment]
You are missing the kernel-headers package. Install it with "apt-get"
