### ISSUE TITLE
Not detecting

### ISSUE THREAD

**Issue by chiragvshroff** [kimocoder/rtl8188eus#13]
i was using these drivers all these days no issues at all but today the adapter is not appearing in airmon-ng but in lsusb the adapter is shown with name 
it not showing itself anywhere 
ex airmon-ng
iwconfig
ipconfig
plzzz help
thank you

**Comment by kimocoder** [comment]
Use the https://github.com/aircrack-ng/rtl8188eus repo, not this one..

**Comment by kimocoder** [comment]
@chiragvshroff 

Check "lsusb" and give me the output there. Also, you can give me output from "airmon-ng"
Then I'll find the VID/PID's that needs to be added. Thanks!
