### ISSUE TITLE
i am getting this error when i put the command make && make install

### ISSUE THREAD

**Issue by chiragvshroff** [kimocoder/rtl8188eus#14]
/bin/sh: 1: bc: not found
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.14.98-v7+/build M=/home/pi/rtl8188eus  modules
make[1]: *** /lib/modules/4.14.98-v7+/build: No such file or directory.  Stop.
Makefile:2061: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by kimocoder** [comment]
You are missing the kernel-headers package.. install it before you may compile drivers.
