### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by chiragvshroff** [kimocoder/rtl8188eus#16]
im using these drivers they are amazing but the issue is i have to type iwconfig wlan0 mode monitor to make it work is there a way to make it work with this command airmon-ng start wlan0??

**Comment by kimocoder** [comment]
I sent a PR to airmon-ng, but it haven't been added yet

**Comment by kimocoder** [comment]
@chiragvshroff 

Git clone my aircrack-ng fork, which has 2 airmon-ng fixes, one that improves the code and the other adding support for rtl8188eus.

here goes https://github.com/kimocoder/aircrack-ng
