### ISSUE TITLE
[X] ERROR: pcap_activate status -1 in reaver and wash

### ISSUE THREAD

**Issue by moham96** [kimocoder/rtl8188eus#3]
Hi,
I get these errors in `reaver` and `wash`

```
[X] ERROR: pcap_activate status -1
[X] PCAP: generic error code
couldn't get pcap handle, exiting
```

similar to https://github.com/t6x/reaver-wps-fork-t6x/issues/265 ?

Regards

**Comment by kimocoder** [comment]
Correct

**Comment by moham96** [comment]
@kimocoder , oh so you already investigated it? any idea what's causing it or a possible solution?

Regards

**Comment by soygalla** [comment]
Is there any fix or workaround?

**Comment by BriefHeart** [comment]
I also have this issue. 
I saw this fix `if (handle) {
		pcap_set_snaplen(handle, 65536);
		pcap_set_timeout(handle, 50);
		pcap_set_rfmon(handle, 0);
		pcap_set_promisc(handle, 0);
		if(!(status = pcap_activate(handle)))
			return handle;
		if(status == PCAP_ERROR_RFMON_NOTSUP) {
			pcap_set_rfmon(handle, 0);
			status = pcap_activate(handle);
			if(!status) return handle;
		}`

But I have no idea what file to edit or where to enter this code???

**Comment by moham96** [comment]
@BriefHeart The code you posted is a userspace code and not kernel driver code, and it's already merged in reaver
https://github.com/t6x/reaver-wps-fork-t6x/blob/feb454c4d93bb332eb8273c9493d54a030cd8cf7/src/init.c#L141-L152

**Comment by moham96** [comment]
Ok, I don't remember what was the version of reaver that i tested with when i faced the issue but right now compiling the master branch of https://github.com/t6x/reaver-wps-fork-t6x I don't get the issue
can you guys confirm that it is fixed ?

**Comment by moham96** [comment]
Ok this is the fix that was merged https://github.com/t6x/reaver-wps-fork-t6x/commit/feb454c4d93bb332eb8273c9493d54a030cd8cf7
I can't make more testing on the device for now so I only tested that wash can scan networks and didn't try any attacks.
I will close this issue, but if someone did more testing and still have the issue we can re-open it

**Comment by BriefHeart** [comment]
@moham96 OMG thank you! This solved it. I've been trying to figure this out for 2 days now. You made my day!!!

**Comment by shahriar-robin** [comment]
> @moham96 OMG thank you! This solved it. I've been trying to figure this out for 2 days now. You made my day!!!

how did you solve that bro, can you explain

**Comment by nowaynear** [comment]
how to solve this please let me know if you have a solution
